### PR TITLE
Update GUIDE.md

### PR DESCRIPTION
**Pull request by i0cus**
Adds two empty lines to make their code-blocks appear in the document.

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks! Can you change "Added" to "Adds" in the commit message?

**Comment by i0cus** [comment]
Done.

**Comment by weavejester** [comment]
It doesn't appear to have changed?

**Comment by i0cus** [comment]
Oh silly me, edited the wrong thing. Can this be edited at this point, or should I do another PR?

**Comment by i0cus** [comment]
Cloned the fork to local and amended the commit, does that work?

(Sorry for the delay, should've done that to begin with instead of using the web fork/edit/PR thing.)

**Comment by weavejester** [comment]
Thanks! But you've somehow removed the commit subject line as well. Can you add it back in? Or change the commit to something more like:

    Fix code blocks in GUIDE.rst

For reference, I follow the standard [seven rules](https://chris.beams.io/posts/git-commit/#seven-rules) for my commit messages.

**Comment by i0cus** [comment]
Check now, please.

**Comment by weavejester** [comment]
Perfect, thanks!

**Pull request merged**
